server:
  port: 8087
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: hello-provider
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://koreyoshi.work:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 39.108.161.215
