server:
  port: 8087
  tomcat:
    uri-encoding: utf-8
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://koreyoshi.work:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

# 调用链 Sleuth + ZipKin
spring:
  application:
    name: hello-provider-zip
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0
  zipkin:
    base-url: http://localhost:9001/ # 指定了Zipkin服务器的地址